<?php

namespace App\DataFixtures;

use App\Entity\Produit\Produit;
use App\Entity\Admin\Fournisseur;
use App\Entity\Produit\Categorie;
use App\Entity\Unite\Unite;
use App\Entity\Unite\Conditionnement;
use App\Entity\Stock\Lot; // Added
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;
use Faker\Factory;

class ProduitFixtures extends Fixture implements DependentFixtureInterface
{
    public function load(ObjectManager $manager): void
    {
        $faker = Factory::create('fr_FR');

        // Récupération des catégories selon le format de CategorieFixtures
        $categories = [];
        $categorieReferences = [
            'medicaments', 'antiparasitaires', 'antibiotiques', 'vaccins', 'anti-inflammatoires', 'vermifuges',
            'alimentation', 'croquettes', 'patees', 'complements-alimentaires', 'aliments-medicalises',
            'hygiene-et-soins', 'shampoings', 'soins-des-yeux-et-oreilles', 'brosses-et-peignes', 'produits-dentaires',
            'accessoires', 'laisses-et-colliers', 'jouets', 'gamelles-et-distributeurs', 'cages-et-transport',
            'materiel-medical', 'seringues-et-aiguilles', 'pansements-et-bandages', 'instruments-chirurgicaux', 'thermometres'
        ];

        foreach ($categorieReferences as $refName) {
            $referenceName = 'categorie_' . $refName;
            if ($this->hasReference($referenceName, Categorie::class)) {
                $categories[] = $this->getReference($referenceName, Categorie::class);
            }
        }

        // Récupération des fournisseurs selon le format de FournisseurFixtures
        $fournisseurs = [];
        $fournisseurReferences = [
            'vetopharma-distribution',
            'centravet',
            'zoetis-france',
            'boehringer-ingelheim-animal-health',
            'elanco',
            'msd-sante-animale',
            'ceva-sante-animale'
        ];

        foreach ($fournisseurReferences as $refName) {
            $referenceName = 'fournisseur_' . $refName;
            if ($this->hasReference($referenceName, Fournisseur::class)) {
                $fournisseurs[] = $this->getReference($referenceName, Fournisseur::class);
            }
        }

        // Récupération des unités selon le format de UniteFixtures
        $unites = [];
        $uniteReferences = [
            'mg', 'g', 'kg', 'ml', 'cl', 'l', 'u', 'cp', 'gél', 'pip', 'sachet', 'flacon', 'boîte', 'tube', 'spray'
        ];

        foreach ($uniteReferences as $refName) {
            $referenceName = 'unite_' . $refName;
            if ($this->hasReference($referenceName, Unite::class)) {
                $unites[] = $this->getReference($referenceName, Unite::class);
            }
        }

        // Fallback: récupération depuis la base de données si les références ne sont pas trouvées
        if (empty($categories)) {
            $categories = $manager->getRepository(Categorie::class)->findAll();
        }
        if (empty($unites)) {
            $unites = $manager->getRepository(Unite::class)->findAll();
        }
        if (empty($fournisseurs)) {
            $fournisseurs = $manager->getRepository(Fournisseur::class)->findAll();
        }

        if (empty($categories) || empty($unites) || empty($fournisseurs)) {
            throw new \Exception('Impossible de charger les fixtures Produit: certaines dépendances sont manquantes (Catégories, Unités ou Fournisseurs)');
        }

        for ($i = 0; $i < 25; $i++) {
            $produit = new Produit();

            $produit->setNom($faker->words(3, true));
            $produit->setDescription($faker->sentence(10));
            // Code will be generated by PrePersist
            
            $produit->setPrixVente($faker->randomFloat(2, 5, 200)); // Adjusted range after removing prixAchat
            $produit->setStockMinimum($faker->numberBetween(10, 30));

            $baseUnit = $faker->randomElement($unites);
            $produit->setCategorie($faker->randomElement($categories));
            $produit->setUniteDeBase($baseUnit);
            $produit->setFournisseur($faker->randomElement($fournisseurs));

            $manager->persist($produit);

            // Create a Lot for the product
            $lot = new Lot();
            $lot->setProduit($produit);
            $lot->setQuantite($faker->numberBetween(50, 200)); // Corresponds to old stockInitial
            $lot->setPrixAchat($faker->randomFloat(2, 5, 100)); // Old prixAchat
            if ($faker->boolean(70)) {
                $lot->setDatePeremption($faker->dateTimeBetween('+6 months', '+3 years')); // Old datePeremption
            }
            if ($faker->boolean(50)) { // Add a lot number for some batches
                $lot->setNumeroLot($faker->unique()->numerify('LOT-####'));
            }
            $manager->persist($lot);

            // Créer des conditionnements
            $otherUnits = array_filter($unites, fn($u) => $u !== $baseUnit);
            if (!empty($otherUnits)) {
                $numberOfConditionnements = $faker->numberBetween(0, min(2, count($otherUnits)));
                
                if ($numberOfConditionnements > 0) {
                    $chosenUnits = $faker->randomElements($otherUnits, $numberOfConditionnements);

                    foreach ($chosenUnits as $targetUnit) {
                        $conditionnement = new Conditionnement();
                        $conditionnement->setProduit($produit);
                        $conditionnement->setUnite($targetUnit);
                        $conditionnement->setQuantite($faker->numberBetween(1, 100));
                        $manager->persist($conditionnement);
                    }
                }
            }

            // Ajouter une référence pour le produit
            $this->addReference('produit_' . $i, $produit);
        }

        $manager->flush();
    }

    public function getDependencies(): array
    {
        return [
            CategorieFixtures::class,
            UniteFixtures::class,
            ConversionStandardFixtures::class,
            FournisseurFixtures::class,
            UserFixtures::class,
        ];
    }
}